plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpEnableEsmLoader: true

pnpEnableInlining: false

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  'bogon@*':
    dependencies:
      'b4a': '*'
